"""15-min model forecast: the model's native 15-minute frames (T+0 .. T+3 h, 13 frames) from the SAME cached run
that /nowcast summarises at hourly steps. Nothing is recomputed per frame and no new forecasting is done.

Resolution notes (reported in every response):
  * flood states come from the prototype's 15-minute model timestep;
  * rainfall input is hourly (design storm or Open-Meteo) and held constant within each hour;
  * live weather-model input is cached for 10 minutes (app.live_rain), so a refresh can pick up new data every 10 min.

Payload: per frame only what the dashboard needs (risk class, depth, depth class, node utilisation, counts and the
rainfall step value). Per-cell rainfall = step value x the model's spatial pattern (sent once). Per-cell scores and
factor contributions are served per selected cell by cell_timeline().
"""
from __future__ import annotations
import numpy as np

import model

LIVE_CACHE_S = 600
NOTE = ("Flood states are generated by the prototype's 15-minute model timestep. "
        "Live weather-model input is refreshed/cached on a 10-minute cycle.")


def resolution() -> dict:
    return dict(model_dt_min=model.DT_MIN, frames=len(range(0, model.FCST_HOURS * 60 + 1, model.DT_MIN)),
                rain_input="hourly intensity held constant within each hour (no sub-hourly rainfall data)",
                live_cache_s=LIVE_CACHE_S, note=NOTE)


def _alerts(m, f, lead, max_n: int = 30) -> dict:
    """Same rule as model.alerts (one alert per drainage sub-catchment at its worst High/Severe cell), for any frame.
    Place names are looked up only for the listed items."""
    best = {}
    for k in np.where(f["cls"] >= 2)[0]:
        n = int(m.cnode[k])
        if n not in best or f["score"][k] > f["score"][best[n]]:
            best[n] = k
    items = []
    for n, k in best.items():
        cell = int(m.idx[k]); lon, lat = m.city.cell_center(*divmod(cell, m.city.nx))
        items.append(dict(cell=cell, node=n, lon=round(lon, 5), lat=round(lat, 5), cls=model.CLASSES[int(f["cls"][k])],
                          score=int(round(f["score"][k])), depth_cm=int(round(f["depth"][k] * 100)),
                          lead_min=int(lead[k]), util=round(float(f["util"][n]), 2)))
    items.sort(key=lambda x: (-model.CLASSES.index(x["cls"]), -x["score"]))
    items = items[:max_n]
    for it in items:
        it["place"] = m.place_name(it["lon"], it["lat"])
    return dict(t_min=f["t_min"], total=len(best), items=items)


def timeline(city_id: str, sc: model.Scenario) -> dict:
    m = model.get_model(city_id); r = model.run_scenario(city_id, sc)
    rain, s0 = r["rain_series"], r["t0"] - 1          # frame i is the state at the end of model step s0 + i
    frames = []
    for i, f in enumerate(r["frames"]):
        counts = [int((f["cls"] == c).sum()) for c in range(4)]
        frames.append(dict(
            t_min=f["t_min"],
            cls=f["cls"].astype(int).tolist(),
            depth_cm=np.round(f["depth"] * 100).astype(int).tolist(),
            depth_cls=np.searchsorted(model.DEPTH_T, f["depth"], side="right").astype(int).tolist(),
            node_util=np.round(f["util"], 2).tolist(),
            tide=round(f["tide"], 2),
            counts=counts, high_severe=counts[2] + counts[3],
            rain_mmph=round(float(rain[s0 + i]), 2),
        ))
    return dict(city=city_id, cells=m.idx.tolist(), rain_pattern=np.round(m.pattern, 3).tolist(), frames=frames,
                lead_min=r["lead_min"].astype(int).tolist(),
                alerts=[_alerts(m, f, r["lead_min"]) for f in r["frames"]], resolution=resolution())


def cell_timeline(city_id: str, sc: model.Scenario, cell: int) -> dict:
    """model.cell_detail with the explanation timeline at every 15-min frame (same fields per entry)."""
    out = model.cell_detail(city_id, sc, cell)          # validates the cell; static, node and lead time
    m = model.get_model(city_id); r = model.run_scenario(city_id, sc)
    k = int(np.searchsorted(m.idx, cell)); n = int(m.cnode[k])
    tl = []
    for f in r["frames"]:
        contrib = sorted(((key, lab, round(float(f["contrib"][key][k]), 1)) for key, lab, _ in model.FACTORS),
                         key=lambda x: -x[2])
        tl.append(dict(
            t_min=f["t_min"], score=round(float(f["score"][k]), 1), cls=model.CLASSES[int(f["cls"][k])],
            depth_cm=round(float(f["depth"][k]) * 100), rain_mmph=round(float(f["rain"][k]), 1),
            cum_mm=round(float(f["cum"][k]), 1), util=round(float(f["util"][n]), 2),
            surcharge_m3=round(float(f["store"][n])), tide=round(f["tide"], 2),
            contributions=[dict(key=a, label=b, points=c) for a, b, c in contrib]))
    out["timeline"] = tl
    out["resolution"] = resolution()
    return out
